In [1]:
import numpy as np
import pandas as pd
import twosigmafunc

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
train, origin_features = twosigmafunc.preprocess()

In [8]:
train.head()

,id,timestamp,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_36,technical_37,technical_38,technical_39,technical_40,technical_41,technical_42,technical_43,technical_44,y
0,10,0,0.370326,-0.006316,0.222831,-0.213030,0.729277,-0.335633,0.113292,1.621238,...,0.775208,NaN,NaN,NaN,-0.414776,NaN,NaN,-2.0,NaN,-0.011753
1,11,0,0.014765,-0.038064,-0.017425,0.320652,-0.034134,0.004413,0.114285,-0.210185,...,0.025590,NaN,NaN,NaN,-0.273607,NaN,NaN,-2.0,NaN,-0.001240
2,12,0,-0.010622,-0.050577,3.379575,-0.157525,-0.068550,-0.155937,1.219439,-0.764516,...,0.151881,NaN,NaN,NaN,-0.175710,NaN,NaN,-2.0,NaN,-0.020940
3,25,0,NaN,NaN,NaN,NaN,NaN,0.178495,NaN,-0.007262,...,1.035936,NaN,NaN,NaN,-0.211506,NaN,NaN,-2.0,NaN,-0.015959
4,26,0,0.176693,-0.025284,-0.057680,0.015100,0.180894,0.139445,-0.125687,-0.018707,...,0.630232,NaN,NaN,NaN,-0.001957,NaN,NaN,0.0,NaN,-0.007338

In [4]:
twosigmafunc.add_nans(train, origin_features)

sucessfully add 108 nan features

In [5]:
train = train.fillna(train.median())

In [6]:
train.head()

,id,timestamp,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_36_nan,technical_37_nan,technical_38_nan,technical_39_nan,technical_40_nan,technical_41_nan,technical_42_nan,technical_43_nan,technical_44_nan,null_count
0,10,0,0.370326,-0.006316,0.222831,-0.213030,0.729277,-0.335633,0.113292,1.621238,...,0,1,1,1,0,1,1,0,1,24
1,11,0,0.014765,-0.038064,-0.017425,0.320652,-0.034134,0.004413,0.114285,-0.210185,...,0,1,1,1,0,1,1,0,1,22
2,12,0,-0.010622,-0.050577,3.379575,-0.157525,-0.068550,-0.155937,1.219439,-0.764516,...,0,1,1,1,0,1,1,0,1,28
3,25,0,-0.000837,0.005523,0.021095,0.002476,0.011752,0.178495,-0.007395,-0.007262,...,0,1,1,1,0,1,1,0,1,38
4,26,0,0.176693,-0.025284,-0.057680,0.015100,0.180894,0.139445,-0.125687,-0.018707,...,0,1,1,1,0,1,1,0,1,21

In [7]:
twosigmafunc.add_diffs(train, origin_features)

sucessfully add 108 diff features

In [8]:
train.head()

,id,timestamp,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_35_diff,technical_36_diff,technical_37_diff,technical_38_diff,technical_39_diff,technical_40_diff,technical_41_diff,technical_42_diff,technical_43_diff,technical_44_diff
131062,0,167,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,...,0.000000,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0
131895,0,168,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,...,0.000000,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0
132728,0,169,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,...,0.000000,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0
133561,0,170,-0.230583,0.488096,0.935920,0.028222,-0.083071,-0.240929,-0.007395,0.212425,...,0.653616,0.81268,3.951567e-12,1.418487e-13,1.591224e-16,-0.14571,0.0,0.0,0.659754,0.0
134393,0,171,-0.230583,0.488096,0.935920,0.028222,-0.083071,-0.240929,-0.007395,0.212425,...,0.000000,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0

In [11]:
train['tec20-30'] = train.technical_20 - train.technical_30

# Get train and test data

In [12]:
X_train, y_train, X_test, y_test = twosigmafunc.split_data(train, twosigmafunc.origin_features(train))

In [13]:
lr_features = ['tec20-30', 'technical_20_diff']

In [14]:
X_train.head()

,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,fundamental_3,fundamental_5,...,technical_36_diff,technical_37_diff,technical_38_diff,technical_39_diff,technical_40_diff,technical_41_diff,technical_42_diff,technical_43_diff,technical_44_diff,tec20-30
131062,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,-0.040183,0.033375,...,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0,0.0
131895,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,-0.040183,0.033375,...,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0,0.0
132728,-0.000837,0.005523,0.021095,0.002476,0.011752,-0.040645,-0.007395,-0.030291,-0.040183,0.033375,...,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0,0.0
133561,-0.230583,0.488096,0.935920,0.028222,-0.083071,-0.240929,-0.007395,0.212425,-0.178111,-0.126889,...,0.81268,3.951567e-12,1.418487e-13,1.591224e-16,-0.14571,0.0,0.0,0.659754,0.0,0.0
134393,-0.230583,0.488096,0.935920,0.028222,-0.083071,-0.240929,-0.007395,0.212425,-0.178111,-0.126889,...,0.00000,0.000000e+00,0.000000e+00,0.000000e+00,0.00000,0.0,0.0,0.000000,0.0,0.0

In [15]:
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.linear_model import LinearRegression

In [16]:
etr0 = ExtraTreesRegressor(n_estimators=128, n_jobs=-1, max_depth=6, max_features=0.5, random_state=1)

In [18]:
etr0.fit(X_train, y_train)
y_etr = etr0.predict(X_test)

In [19]:
twosigmafunc.R_score(y_etr, y_test)

0.022155382930328673

In [20]:
lr = LinearRegression(n_jobs=-1)
lr.fit(X_train[lr_features], y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

In [21]:
X_train['y_lr'] = lr.predict(X_train[lr_features])
X_test['y_lr'] = lr.predict(X_test[lr_features])

In [23]:
etr1 = ExtraTreesRegressor(n_estimators=128, n_jobs=-1, max_depth=6, max_features=0.5, random_state=1)
etr1.fit(X_train, y_train)
y_etr1 = etr1.predict(X_test)
twosigmafunc.R_score(y_etr1, y_test)

0.024996392560050096

In [26]:
imp = pd.DataFrame({'feature':X_test.columns, 'important':etr1.feature_importances_}).sort_values('important', ascending=0)

In [27]:
imp

                 feature  important
326                 y_lr   0.045585
325             tec20-30   0.043090
93          technical_30   0.040949
323    technical_43_diff   0.033182
106         technical_43   0.032876
294    technical_11_diff   0.027334
70           technical_2   0.027287
77          technical_11   0.026873
85          technical_20   0.026591
290     technical_6_diff   0.022940
73           technical_6   0.021424
287     technical_2_diff   0.019999
15        fundamental_11   0.019086
310    technical_30_diff   0.018070
297    technical_14_diff   0.017009
303    technical_21_diff   0.014848
86          technical_21   0.013831
74           technical_7   0.012999
137   fundamental_25_nan   0.012873
299    technical_17_diff   0.012844
80          technical_14   0.011256
215     technical_44_nan   0.011046
302    technical_20_diff   0.010480
103         technical_40   0.010438
84          technical_19   0.010414
82          technical_17   0.010371
12         fundamental_8   0.009732
139   fundamental_27_nan   0.008812
55        fundamental_51   0.007948
57        fundamental_53   0.007476
..                   ...        ...
227   fundamental_6_diff   0.000024
249  fundamental_28_diff   0.000012
123   fundamental_11_nan   0.000002
194     technical_21_nan   0.000000
156   fundamental_44_nan   0.000000
167   fundamental_55_nan   0.000000
162   fundamental_50_nan   0.000000
205     technical_34_nan   0.000000
198     technical_27_nan   0.000000
168   fundamental_56_nan   0.000000
206     technical_35_nan   0.000000
158   fundamental_46_nan   0.000000
191     technical_18_nan   0.000000
304    technical_22_diff   0.000000
128   fundamental_16_nan   0.000000
190     technical_17_nan   0.000000
142   fundamental_30_nan   0.000000
185     technical_11_nan   0.000000
126   fundamental_14_nan   0.000000
141   fundamental_29_nan   0.000000
127   fundamental_15_nan   0.000000
192     technical_19_nan   0.000000
207     technical_36_nan   0.000000
182      technical_7_nan   0.000000
282  fundamental_61_diff   0.000000
149   fundamental_37_nan   0.000000
65        fundamental_61   0.000000
211     technical_40_nan   0.000000
300    technical_18_diff   0.000000
195     technical_22_nan   0.000000

[327 rows x 2 columns]