In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
train = pd.read_hdf('train.h5')
train = train[['id','derived_0', 'derived_1', 'derived_2']]

In [3]:
id_group = train.groupby('id').mean()

In [4]:
id_group

      derived_0  derived_1  derived_2
id
0      0.007053   0.094208  -0.004151
6      0.431738   0.061654   0.262803
7     -0.214595   0.553051   0.897718
10     0.150048  -0.000719   0.229835
11    -0.003351  -0.049996   0.727804
12    -0.009566  -0.044197   0.561202
13    -0.017893  -0.044672        NaN
14     0.061960  -0.008491        NaN
15    -0.110657   0.086306        NaN
16    -0.380247   1.320205   0.449123
17     0.130974   0.024882   0.137047
18    -0.001360  -0.049794  -0.044251
19     0.071251   0.454160  -0.350578
20     0.042606  -0.031878  -0.013583
22    -0.056028   0.013500  -0.003975
23     0.981826   0.169952   0.076517
24     0.051042   0.040880   0.051310
25     0.107341  -0.005704   0.001264
26     0.052669  -0.012903  -0.012224
27     0.334182   0.180035  -1.442517
30    -0.199610   0.230793   0.185684
31    -0.106400   0.038725        NaN
32    -0.013459  -0.011342   0.043834
33     0.035514  -0.026802  -0.026130
38    -0.036409  -0.011771  -0.033331
39     0.006196  -0.036066   0.325938
40    -0.105956   0.171249  -1.068242
41     0.082378   1.354627   0.082877
43     0.043813   0.047561   0.025620
44    -0.001300  -0.038366   2.901053
...         ...        ...        ...
2115   2.827655   0.264532  -2.424397
2117  -6.021380   0.073558  -0.869254
2118  -0.334335   0.899400        NaN
2120        NaN        NaN  -0.402105
2121   0.016476   0.039497        NaN
2124  -0.236558  -0.017344        NaN
2125  -0.469590   0.115183   0.411052
2126  -0.015744  -0.045175   0.050398
2129  -0.009117  -0.030031        NaN
2130  -0.466907   0.302342   0.248878
2131   0.053083   0.757488  -0.088492
2134  -0.084492   0.071785  -0.686949
2135   0.007524  -0.006620   0.005976
2136   0.044059   0.009790        NaN
2137  -0.015746  -0.028396   0.007951
2138  -0.006389  -0.016367   0.032789
2139  -0.038811   2.253181  -0.928297
2140  -0.016207  -0.005534        NaN
2142   0.031105  -0.034496  -0.041981
2145   0.034337  -0.026424   0.024955
2146  -0.196211   0.263057   0.547209
2148  -0.008609  -0.041586   0.427679
2149   0.025889   0.093487   0.250251
2150  -0.043497  -0.045122        NaN
2151  -0.067627   0.352395        NaN
2152   1.061498   0.141069   7.673058
2154   0.008365  -0.025769   0.182606
2155  -0.012658  -0.049118        NaN
2156  -0.038569  -0.041280        NaN
2158        NaN        NaN        NaN

[1424 rows x 3 columns]

In [5]:
id_mean = id_group.mean(axis=0)
id_mean

derived_0   -6.047383e+00
derived_1    8.475017e+11
derived_2   -3.157867e-01
dtype: float32

In [6]:
id_group.fillna(id_mean, inplace=True)

      derived_0     derived_1  derived_2
id
0      0.007053  9.420843e-02  -0.004151
6      0.431738  6.165408e-02   0.262803
7     -0.214595  5.530509e-01   0.897718
10     0.150048 -7.190892e-04   0.229835
11    -0.003351 -4.999639e-02   0.727804
12    -0.009566 -4.419670e-02   0.561202
13    -0.017893 -4.467184e-02  -0.315787
14     0.061960 -8.491025e-03  -0.315787
15    -0.110657  8.630566e-02  -0.315787
16    -0.380247  1.320205e+00   0.449123
17     0.130974  2.488207e-02   0.137047
18    -0.001360 -4.979350e-02  -0.044251
19     0.071251  4.541602e-01  -0.350578
20     0.042606 -3.187832e-02  -0.013583
22    -0.056028  1.349988e-02  -0.003975
23     0.981826  1.699515e-01   0.076517
24     0.051042  4.087989e-02   0.051310
25     0.107341 -5.704210e-03   0.001264
26     0.052669 -1.290348e-02  -0.012224
27     0.334182  1.800349e-01  -1.442517
30    -0.199610  2.307930e-01   0.185684
31    -0.106400  3.872531e-02  -0.315787
32    -0.013459 -1.134208e-02   0.043834
33     0.035514 -2.680218e-02  -0.026130
38    -0.036409 -1.177139e-02  -0.033331
39     0.006196 -3.606585e-02   0.325938
40    -0.105956  1.712486e-01  -1.068242
41     0.082378  1.354627e+00   0.082877
43     0.043813  4.756079e-02   0.025620
44    -0.001300 -3.836621e-02   2.901053
...         ...           ...        ...
2115   2.827655  2.645319e-01  -2.424397
2117  -6.021380  7.355832e-02  -0.869254
2118  -0.334335  8.993997e-01  -0.315787
2120  -6.047383  8.475017e+11  -0.402105
2121   0.016476  3.949732e-02  -0.315787
2124  -0.236558 -1.734411e-02  -0.315787
2125  -0.469590  1.151828e-01   0.411052
2126  -0.015744 -4.517472e-02   0.050398
2129  -0.009117 -3.003054e-02  -0.315787
2130  -0.466907  3.023420e-01   0.248878
2131   0.053083  7.574881e-01  -0.088492
2134  -0.084492  7.178546e-02  -0.686949
2135   0.007524 -6.620207e-03   0.005976
2136   0.044059  9.790070e-03  -0.315787
2137  -0.015746 -2.839580e-02   0.007951
2138  -0.006389 -1.636676e-02   0.032789
2139  -0.038811  2.253181e+00  -0.928297
2140  -0.016207 -5.533738e-03  -0.315787
2142   0.031105 -3.449629e-02  -0.041981
2145   0.034337 -2.642447e-02   0.024955
2146  -0.196211  2.630567e-01   0.547209
2148  -0.008609 -4.158581e-02   0.427679
2149   0.025889  9.348705e-02   0.250251
2150  -0.043497 -4.512232e-02  -0.315787
2151  -0.067627  3.523954e-01  -0.315787
2152   1.061498  1.410687e-01   7.673058
2154   0.008365 -2.576923e-02   0.182606
2155  -0.012658 -4.911805e-02  -0.315787
2156  -0.038569 -4.127976e-02  -0.315787
2158  -6.047383  8.475017e+11  -0.315787

[1424 rows x 3 columns]

In [17]:
id_group.loc[54]

derived_0   -0.096494
derived_1   -0.030667
derived_2   -0.315787
Name: 54, dtype: float32

In [26]:
train_sm = train[0:20]

In [27]:
train_sm

    id  derived_0  derived_1  derived_2
0   10   0.370326  -0.006316   0.222831
1   11   0.014765  -0.038064  -0.017425
2   12  -0.010622  -0.050577   3.379575
3   25        NaN        NaN        NaN
4   26   0.176693  -0.025284  -0.057680
5   27   0.346856   0.166239  -6.080701
6   31   0.072036   0.014931        NaN
7   38   0.300062   0.071251  -0.074451
8   39  -0.003511  -0.034270   0.082372
9   40  -0.083330   0.081935  -2.048438
10  41   0.435826   1.797289   0.363570
11  43        NaN        NaN        NaN
12  44   0.034991  -0.019258   0.055769
13  49        NaN   0.212615  -0.979520
14  54   0.071704  -0.044019        NaN
15  59   0.116360   0.164506   0.156510
16  60   0.026824  -0.024105  -0.028991
17  62   0.367122   0.675543  -0.008483
18  63   0.453271  -0.036301   0.094657
19  68  -0.122734   0.038939   0.148015

In [28]:
train_sm['index_copy'] = train_sm.index

/usr/local/lib/python3.4/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [21]:
train_sm

    id  derived_0  derived_1  derived_2  index_copy
0   10   0.370326  -0.006316   0.222831           0
1   11   0.014765  -0.038064  -0.017425           1
2   12  -0.010622  -0.050577   3.379575           2
3   25        NaN        NaN        NaN           3
4   26   0.176693  -0.025284  -0.057680           4
5   27   0.346856   0.166239  -6.080701           5
6   31   0.072036   0.014931        NaN           6
7   38   0.300062   0.071251  -0.074451           7
8   39  -0.003511  -0.034270   0.082372           8
9   40  -0.083330   0.081935  -2.048438           9
10  41   0.435826   1.797289   0.363570          10
11  43        NaN        NaN        NaN          11
12  44   0.034991  -0.019258   0.055769          12
13  49        NaN   0.212615  -0.979520          13
14  54   0.071704  -0.044019        NaN          14
15  59   0.116360   0.164506   0.156510          15
16  60   0.026824  -0.024105  -0.028991          16
17  62   0.367122   0.675543  -0.008483          17
18  63   0.453271  -0.036301   0.094657          18
19  68  -0.122734   0.038939   0.148015          19

In [18]:
for idd in train_sm.id:
    row = train_sm.loc[train_sm.id==idd].fillna(id_group.loc[idd], inplace=True)
    print(row)

/usr/local/lib/python3.4/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/usr/local/lib/python3.4/site-packages/pandas/core/frame.py:3847: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  raise_on_error=True)

   id  derived_0  derived_1  derived_2
0  10   0.370326  -0.006316   0.222831
   id  derived_0  derived_1  derived_2
1  11   0.014765  -0.038064  -0.017425
   id  derived_0  derived_1  derived_2
2  12  -0.010622  -0.050577   3.379575
   id  derived_0  derived_1  derived_2
3  25   0.107341  -0.005704   0.001264
   id  derived_0  derived_1  derived_2
4  26   0.176693  -0.025284   -0.05768
   id  derived_0  derived_1  derived_2
5  27   0.346856   0.166239  -6.080701
   id  derived_0  derived_1  derived_2
6  31   0.072036   0.014931  -0.315787
   id  derived_0  derived_1  derived_2
7  38   0.300062   0.071251  -0.074451
   id  derived_0  derived_1  derived_2
8  39  -0.003511   -0.03427   0.082372
   id  derived_0  derived_1  derived_2
9  40   -0.08333   0.081935  -2.048438
    id  derived_0  derived_1  derived_2
10  41   0.435826   1.797289    0.36357
    id  derived_0  derived_1  derived_2
11  43   0.043813   0.047561    0.02562
    id  derived_0  derived_1  derived_2
12  44   0.034991  -0.019258   0.055769
    id  derived_0  derived_1  derived_2
13  49  -6.047383   0.212615   -0.97952
    id  derived_0  derived_1  derived_2
14  54   0.071704  -0.044019  -0.315787
    id  derived_0  derived_1  derived_2
15  59    0.11636   0.164506    0.15651
    id  derived_0  derived_1  derived_2
16  60   0.026824  -0.024105  -0.028991
    id  derived_0  derived_1  derived_2
17  62   0.367122   0.675543  -0.008483
    id  derived_0  derived_1  derived_2
18  63   0.453271  -0.036301   0.094657
    id  derived_0  derived_1  derived_2
19  68  -0.122734   0.038939   0.148015

In [29]:
train_sm = train_sm.set_index('id').sort_index()

In [30]:
train_sm

    derived_0  derived_1  derived_2  index_copy
id
10   0.370326  -0.006316   0.222831           0
11   0.014765  -0.038064  -0.017425           1
12  -0.010622  -0.050577   3.379575           2
25        NaN        NaN        NaN           3
26   0.176693  -0.025284  -0.057680           4
27   0.346856   0.166239  -6.080701           5
31   0.072036   0.014931        NaN           6
38   0.300062   0.071251  -0.074451           7
39  -0.003511  -0.034270   0.082372           8
40  -0.083330   0.081935  -2.048438           9
41   0.435826   1.797289   0.363570          10
43        NaN        NaN        NaN          11
44   0.034991  -0.019258   0.055769          12
49        NaN   0.212615  -0.979520          13
54   0.071704  -0.044019        NaN          14
59   0.116360   0.164506   0.156510          15
60   0.026824  -0.024105  -0.028991          16
62   0.367122   0.675543  -0.008483          17
63   0.453271  -0.036301   0.094657          18
68  -0.122734   0.038939   0.148015          19

In [53]:
train_null = train.loc[train.derived_0.isnull()]

In [55]:
train_null = train_null[0:20]

In [56]:
train_null

      id  derived_0  derived_1  derived_2         y
3     25        NaN        NaN        NaN -0.015959
11    43        NaN        NaN        NaN  0.050219
13    49        NaN   0.212615   -0.97952 -0.005203
37   111        NaN        NaN        NaN -0.015709
46   129        NaN        NaN        NaN  0.066793
64   187        NaN        NaN        NaN  0.013825
102  273        NaN        NaN        NaN -0.034454
109  288        NaN        NaN        NaN -0.001300
110  289        NaN        NaN        NaN  0.012519
122  343        NaN        NaN        NaN -0.029305
140  406        NaN        NaN        NaN -0.008944
192  551        NaN        NaN        NaN -0.016650
212  594        NaN        NaN        NaN  0.039996
214  602        NaN        NaN        NaN  0.007819
268  751        NaN        NaN        NaN  0.004122
286  807        NaN        NaN        NaN -0.007830
289  815        NaN        NaN        NaN  0.009717
336  954        NaN        NaN        NaN  0.006119
339  961        NaN        NaN        NaN -0.086094
340  963        NaN        NaN        NaN  0.017675

In [57]:
train_null.fillna(id_mean, inplace=True)

/usr/local/lib/python3.4/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

      id  derived_0  derived_1  derived_2         y
3     25   0.044459   0.148970   0.152333 -0.015959
11    43   0.044459   0.148970   0.152333  0.050219
13    49   0.044459   0.212615  -0.979520 -0.005203
37   111   0.044459   0.148970   0.152333 -0.015709
46   129   0.044459   0.148970   0.152333  0.066793
64   187   0.044459   0.148970   0.152333  0.013825
102  273   0.044459   0.148970   0.152333 -0.034454
109  288   0.044459   0.148970   0.152333 -0.001300
110  289   0.044459   0.148970   0.152333  0.012519
122  343   0.044459   0.148970   0.152333 -0.029305
140  406   0.044459   0.148970   0.152333 -0.008944
192  551   0.044459   0.148970   0.152333 -0.016650
212  594   0.044459   0.148970   0.152333  0.039996
214  602   0.044459   0.148970   0.152333  0.007819
268  751   0.044459   0.148970   0.152333  0.004122
286  807   0.044459   0.148970   0.152333 -0.007830
289  815   0.044459   0.148970   0.152333  0.009717
336  954   0.044459   0.148970   0.152333  0.006119
339  961   0.044459   0.148970   0.152333 -0.086094
340  963   0.044459   0.148970   0.152333  0.017675

In [40]:
sm_train

    derived_0  derived_1  derived_2         y
id
10   0.370326  -0.006316   0.222831 -0.011753
11   0.014765  -0.038064  -0.017425 -0.001240
12  -0.010622  -0.050577   3.379575 -0.020940
25        NaN        NaN        NaN -0.015959
26   0.176693  -0.025284  -0.057680 -0.007338
27   0.346856   0.166239  -6.080701  0.031425
31   0.072036   0.014931        NaN -0.032895
38   0.300062   0.071251  -0.074451  0.015803
39  -0.003511  -0.034270   0.082372 -0.027593
40  -0.083330   0.081935  -2.048438  0.006662
41   0.435826   1.797289   0.363570 -0.001899
43        NaN        NaN        NaN  0.050219
44   0.034991  -0.019258   0.055769 -0.018991
49        NaN   0.212615  -0.979520 -0.005203
54   0.071704  -0.044019        NaN -0.006369
59   0.116360   0.164506   0.156510  0.017768
60   0.026824  -0.024105  -0.028991 -0.001089
62   0.367122   0.675543  -0.008483 -0.008794
63   0.453271  -0.036301   0.094657  0.040724
68  -0.122734   0.038939   0.148015 -0.003921
69  -0.062361  -0.063724   0.021274 -0.011317
70   0.175489  -0.024445  -0.034079  0.044167
76  -0.190705   0.006221  -0.056835  0.001395
79   0.008503   0.048732   0.123793 -0.012101
80   0.043156   0.540945   0.278394 -0.070837
82   0.086832  -0.022962        NaN -0.001766
83  -0.082307  -0.039761   0.102000 -0.012542
85   0.005351  -0.031086   0.078334  0.029697
87   0.045536   0.054391   0.330190  0.030815
90  -0.003925  -0.037522        NaN -0.016336

In [39]:
sm_train.set_index('id', inplace=True)

In [43]:
sm_train.loc[25]

derived_0         NaN
derived_1         NaN
derived_2         NaN
y           -0.015959
Name: 25, dtype: float32

In [14]:
sm_train.loc[sm_train['id']<13]

   id  derived_0  derived_1  derived_2         y
0  10   0.370326  -0.006316   0.222831 -0.011753
1  11   0.014765  -0.038064  -0.017425 -0.001240
2  12  -0.010622  -0.050577   3.379575 -0.020940

In [15]:
sm_t = train_i[0:100]

In [22]:
sm_t[0:10]

    derived_0  derived_1  derived_2         y
id
0   -0.044897   0.261606   0.025084 -0.009050
0    0.349362   0.183633  -0.032296  0.001842
0   -0.064861  -0.051526  -0.071052 -0.027787
0   -0.361402  -0.025774  -0.039979 -0.005913
0   -0.262986   0.082918   0.001214  0.001603
0    0.349353   0.183635  -0.032292 -0.003774
0   -0.361379  -0.025778  -0.039983  0.020174
0    0.399335   0.129828   0.003659  0.006059
0   -0.001574  -0.052373  -0.000185  0.014639
0   -0.309994   0.420446   0.068611 -0.010800

In [35]:
sm_train[1:2]

   id  derived_0  derived_1  derived_2        y
1  11   0.014765  -0.038064  -0.017425 -0.00124

In [30]:
sm_train

    id  derived_0  derived_1  derived_2         y
0   10   0.370326  -0.006316   0.222831 -0.011753
1   11   0.014765  -0.038064  -0.017425 -0.001240
2   12  -0.010622  -0.050577   3.379575 -0.020940
3   25        NaN        NaN        NaN -0.015959
4   26   0.176693  -0.025284  -0.057680 -0.007338
5   27   0.346856   0.166239  -6.080701  0.031425
6   31   0.072036   0.014931        NaN -0.032895
7   38   0.300062   0.071251  -0.074451  0.015803
8   39  -0.003511  -0.034270   0.082372 -0.027593
9   40  -0.083330   0.081935  -2.048438  0.006662
10  41   0.435826   1.797289   0.363570 -0.001899
11  43        NaN        NaN        NaN  0.050219
12  44   0.034991  -0.019258   0.055769 -0.018991
13  49        NaN   0.212615  -0.979520 -0.005203
14  54   0.071704  -0.044019        NaN -0.006369
15  59   0.116360   0.164506   0.156510  0.017768
16  60   0.026824  -0.024105  -0.028991 -0.001089
17  62   0.367122   0.675543  -0.008483 -0.008794
18  63   0.453271  -0.036301   0.094657  0.040724
19  68  -0.122734   0.038939   0.148015 -0.003921
20  69  -0.062361  -0.063724   0.021274 -0.011317
21  70   0.175489  -0.024445  -0.034079  0.044167
22  76  -0.190705   0.006221  -0.056835  0.001395
23  79   0.008503   0.048732   0.123793 -0.012101
24  80   0.043156   0.540945   0.278394 -0.070837
25  82   0.086832  -0.022962        NaN -0.001766
26  83  -0.082307  -0.039761   0.102000 -0.012542
27  85   0.005351  -0.031086   0.078334  0.029697
28  87   0.045536   0.054391   0.330190  0.030815
29  90  -0.003925  -0.037522        NaN -0.016336

In [36]:
id_group.fillna(id_mean, inplace=True)

    derived_0  derived_1  derived_2         y
id
0    0.007053   0.094208  -0.004151  0.000207
6    0.431738   0.061654   0.262803  0.000154
7   -0.214595   0.553051   0.897718  0.000524
10   0.150048  -0.000719   0.229835 -0.000721
11  -0.003351  -0.049996   0.727804  0.000158
12  -0.009566  -0.044197   0.561202  0.000235
13  -0.017893  -0.044672   0.152333 -0.000405
14   0.061960  -0.008491   0.152333  0.000008
15  -0.110657   0.086306   0.152333  0.000467
16  -0.380247   1.320205   0.449123  0.001281
17   0.130974   0.024882   0.137047  0.000914
18  -0.001360  -0.049794  -0.044251 -0.000927
19   0.071251   0.454160  -0.350578 -0.000029
20   0.042606  -0.031878  -0.013583  0.000148
22  -0.056028   0.013500  -0.003975  0.000115
23   0.981826   0.169952   0.076517 -0.000764
24   0.051042   0.040880   0.051310  0.000405
25   0.107341  -0.005704   0.001264  0.000768
26   0.052669  -0.012903  -0.012224  0.000441
27   0.334182   0.180035  -1.442517  0.001500
30  -0.199610   0.230793   0.185684  0.000230
31  -0.106400   0.038725   0.152333  0.000910
32  -0.013459  -0.011342   0.043834  0.000972
33   0.035514  -0.026802  -0.026130  0.000397
38  -0.036409  -0.011771  -0.033331  0.000461
39   0.006196  -0.036066   0.325938  0.000403
40  -0.105956   0.171249  -1.068242  0.000714
41   0.082378   1.354627   0.082877  0.000239
43   0.043813   0.047561   0.025620 -0.000365
44  -0.001300  -0.038366   2.901053  0.000267

In [27]:
sm_train = train_i[24800:24810]

In [28]:
sm_train

    derived_0  derived_1  derived_2         y
id
31   0.277622   0.021679        NaN -0.086094
31  -0.743973   0.040630        NaN -0.010617
31  -0.568080   0.060299        NaN -0.033545
31   0.139646   0.005156        NaN  0.093498
31  -0.752792   0.123466        NaN  0.093498
31  -0.771554   0.097467        NaN -0.073864
31   0.356062   0.016484        NaN  0.001259
31  -0.756311   0.036344        NaN  0.006949
31   0.279749   0.022899        NaN -0.019587
31  -0.579350   0.072268        NaN -0.086094

In [37]:
sm_train.fillna(id_group)

    derived_0  derived_1  derived_2         y
id
31   0.277622   0.021679   0.152333 -0.086094
31  -0.743973   0.040630   0.152333 -0.010617
31  -0.568080   0.060299   0.152333 -0.033545
31   0.139646   0.005156   0.152333  0.093498
31  -0.752792   0.123466   0.152333  0.093498
31  -0.771554   0.097467   0.152333 -0.073864
31   0.356062   0.016484   0.152333  0.001259
31  -0.756311   0.036344   0.152333  0.006949
31   0.279749   0.022899   0.152333 -0.019587
31  -0.579350   0.072268   0.152333 -0.086094